name = "Pookie"
author = "AmeMeida"
version = "3.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e5b6e76a14de8ff57de97dd3d71bfdbf25f80f64358628fac2d38ae17c86e18"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"

[options]
datapack-folder = "config/openloader/data"
