name = "Pookie"
author = "AmeMeida"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a09703f0ddf34236990584848b32fac5fb2918dc30f044eb6678e579137b1074"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
