name = "Pookie"
author = "AmeMeida"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d82825a9ddf56d816571406476c079dc5dce714b6eebe1baa6003a65464375b1"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
